# Generated by Django 4.0.4 on 2022-05-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStockMarketData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('open', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('close', models.FloatField(null=True)),
                ('adj_close', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('sma_50', models.FloatField(null=True)),
                ('sma_200', models.FloatField(null=True)),
                ('bband_h', models.FloatField(null=True)),
                ('bband_l', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'daily_stock_market_data',
            },
        ),
        migrations.CreateModel(
            name='DailyTechnicalAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'daily_technical_analysis',
            },
        ),
        migrations.CreateModel(
            name='StockMarketData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('date_time', models.DateTimeField()),
                ('open', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('close', models.FloatField(null=True)),
                ('adj_close', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'stock_market_data',
            },
        ),
        migrations.CreateModel(
            name='TickerInfo',
            fields=[
                ('ticker', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('company', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'ticker_info',
                'order_with_respect_to': 'ticker',
            },
        ),
    ]
