# Generated by Django 4.0.4 on 2022-05-20 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='tickerinfo',
            order_with_respect_to='ticker',
        ),
        migrations.AlterModelTable(
            name='tickerinfo',
            table='ticker_info',
        ),
    ]
