# Generated by Django 4.0.4 on 2022-05-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_alter_tickerinfo_order_with_respect_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStockMarketData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('adj_close', models.FloatField()),
                ('volume', models.FloatField()),
            ],
            options={
                'db_table': 'daily_stock_market_data',
                'order_with_respect_to': 'date',
            },
        ),
    ]
