# Generated by Django 4.0.4 on 2022-05-28 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_alter_tickerinfo_industry'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='tickerinfo',
            order_with_respect_to=None,
        ),
    ]
