# Generated by Django 4.0.4 on 2022-05-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0003_alter_tickerinfo_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerinfo',
            name='ticker',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
