# Generated by Django 4.0.4 on 2022-05-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0003_dailystockmarketdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmarketdata',
            name='adj_close',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockmarketdata',
            name='close',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockmarketdata',
            name='open',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockmarketdata',
            name='volume',
            field=models.FloatField(null=True),
        ),
    ]
