# Generated by Django 4.0.4 on 2022-05-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0004_alter_stockmarketdata_adj_close_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystockmarketdata',
            name='adj_close',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dailystockmarketdata',
            name='close',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dailystockmarketdata',
            name='open',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dailystockmarketdata',
            name='volume',
            field=models.FloatField(null=True),
        ),
    ]
