# Generated by Django 4.0.4 on 2022-05-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0005_alter_tickerinfo_company_alter_tickerinfo_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystockmarketdata',
            name='ticker',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='dailytechnicalanalysis',
            name='ticker',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='stockmarketdata',
            name='ticker',
            field=models.CharField(max_length=6),
        ),
    ]
