# Generated by Django 4.0.4 on 2022-05-22 07:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0005_alter_dailystockmarketdata_adj_close_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystockmarketdata',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
