# Generated by Django 4.0.4 on 2022-05-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0006_alter_dailystockmarketdata_ticker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystockmarketdata',
            name='rsi',
            field=models.FloatField(null=True),
        ),
    ]
