# Generated by Django 4.0.4 on 2022-05-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0006_alter_dailystockmarketdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystockmarketdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='dailystockmarketdata',
            order_with_respect_to=None,
        ),
    ]
