# Generated by Django 4.0.4 on 2022-05-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0007_alter_dailystockmarketdata_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystockmarketdata',
            name='sma_200',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dailystockmarketdata',
            name='sma_50',
            field=models.FloatField(null=True),
        ),
    ]
