# Generated by Django 4.0.4 on 2022-05-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0008_rename_dailytechnicalanalysis_dailytasignal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailytasignal',
            old_name='category',
            new_name='description',
        ),
        migrations.AddField(
            model_name='dailytasignal',
            name='signal',
            field=models.CharField(default='buy', max_length=5),
            preserve_default=False,
        ),
    ]
