# Generated by Django 4.0.4 on 2022-05-31 18:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0009_rename_category_dailytasignal_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('description', models.CharField(max_length=300, null=True)),
            ],
            options={
                'db_table': 'back_tests',
            },
        ),
        migrations.CreateModel(
            name='BackTestTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('back_test_id', models.UUIDField()),
                ('action', models.CharField(max_length=4)),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=6)),
                ('shares', models.IntegerField()),
                ('price_per_share', models.FloatField()),
            ],
            options={
                'db_table': 'back_test_transactions',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(max_length=4)),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=6)),
                ('shares', models.IntegerField()),
                ('price_per_share', models.FloatField()),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
