# Generated by Django 4.0.4 on 2022-06-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0010_backtest_backtesttransaction_transaction'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailystockmarketdata',
            index=models.Index(fields=['date'], name='daily_stock_date_47baad_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystockmarketdata',
            index=models.Index(fields=['ticker'], name='daily_stock_ticker_43fd30_idx'),
        ),
    ]
